// ============================================================
// demo-deployer/src/config.js — Configuração dos componentes
// ============================================================

export const COMPONENTS = [
  {
    id: "mcp-server-k8s-live",
    name: "MCP Server K8s Live",
    description: "Métricas, pods, deployments, eventos, VPA, bin packing do cluster",
    icon: "📊",
    category: "mcp",
    order: 0,
    namespace: "mcp-server-k8s-live",
    playbook: "deploy-component.yml",
    contextDir: "mcp-server-k8s-live",
    port: 3000,
    envVars: [
      { key: "K8S_API_URL", value: "{{ocp_api_url}}" },
      { key: "K8S_BEARER_TOKEN", value: "{{sa_token}}" },
      { key: "K8S_SKIP_TLS_VERIFY", value: "true" },
    ],
  },
  {
    id: "mcp-server-k8s-security",
    name: "MCP Server K8s Security",
    description: "NetworkPolicies, logs de segurança, namespaces",
    icon: "🛡️",
    category: "mcp",
    order: 1,
    namespace: "mcp-server-k8s-security",
    playbook: "deploy-component.yml",
    contextDir: "mcp-server-k8s-security",
    port: 3000,
    envVars: [
      { key: "K8S_API_URL", value: "{{ocp_api_url}}" },
      { key: "K8S_BEARER_TOKEN", value: "{{sa_token}}" },
      { key: "K8S_SKIP_TLS_VERIFY", value: "true" },
    ],
  },
  {
    id: "mcp-server-downdetector",
    name: "MCP Server Downdetector",
    description: "Verificação de status de websites (uptime/downtime)",
    icon: "🌐",
    category: "mcp",
    order: 2,
    namespace: "mcp-server-downdetector",
    playbook: "deploy-component.yml",
    contextDir: "mcp-server-downdetector",
    port: 3000,
  },
  {
    id: "mcp-server-saude",
    name: "MCP Server Saúde",
    description: "Dados de saúde escolar dos alunos",
    icon: "🏥",
    category: "mcp",
    order: 3,
    namespace: "mcp-server-saude",
    playbook: "deploy-component.yml",
    contextDir: "mcp-server-saude",
    port: 3001,
  },
  {
    id: "mcp-server-matriculas",
    name: "MCP Server Matrículas",
    description: "Dados de matrículas de alunos",
    icon: "🎓",
    category: "mcp",
    order: 4,
    namespace: "mcp-server-matriculas",
    playbook: "deploy-component.yml",
    contextDir: "mcp-server-matriculas",
    port: 3000,
  },
  {
    id: "mcp-server-sei",
    name: "MCP Server SEI",
    description: "Integração com o SEI — consulta e criação de processos e documentos",
    icon: "📄",
    category: "mcp",
    order: 5,
    namespace: "mcp-server-sei",
    playbook: "deploy-component.yml",
    contextDir: "mcp-server-sei",
    port: 3000,
    envVars: [
      { key: "SEI_URL",      value: "{{sei_url}}" },
      { key: "SEI_TOKEN",    value: "{{sei_token}}" },
      { key: "SEI_UNIDADE",  value: "{{sei_unidade}}" },
    ],
  },
  {
    id: "mcp-server-sei-agent",
    name: "MCP Server SEI Agent",
    description: "Agente SEI multi-agent: conecta ao Agente SEI hospedado na OpenAI via Responses API",
    icon: "🏛️",
    category: "mcp",
    order: 6,
    namespace: "mcp-server-sei-agent",
    playbook: "deploy-component.yml",
    contextDir: "mcp-server-sei-agent",
    port: 3000,
    envVars: [
      { key: "OPENAI_API_KEY",           value: "{{openai_api_key}}" },
      { key: "OPENAI_SEI_MODEL",         value: "{{openai_sei_model}}" },
      { key: "OPENAI_SEI_WORKFLOW_ID",   value: "{{openai_sei_workflow_id}}" },
    ],
  },
  {
    id: "imagem-crash",
    name: "Imagem Crash (Demo)",
    description: "Container que entra em CrashLoopBackOff para demonstração",
    icon: "💥",
    category: "demo",
    order: 6,
    namespace: "imagem-crash",
    playbook: "deploy-component.yml",
    contextDir: "imagem-crash",
    port: 8080,
  },
  {
    id: "agent-ai",
    name: "Agent AI (Chatbot)",
    description: "Chatbot Quarkus + LangChain4j com Redis, RBAC e orquestrador principal",
    icon: "🤖",
    category: "core",
    order: 7,
    namespace: "agent-ai",
    playbook: "deploy-component.yml",
    contextDir: "agent-ai",
    port: 8080,
    routeTimeout: true,
    envVars: [
      { key: "REDIS_URL",             value: "redis://redis:6379" },
      { key: "K8S_API_URL",           value: "{{ocp_api_url}}" },
      { key: "K8S_BEARER_TOKEN",      value: "{{sa_token}}" },
      { key: "K8S_SKIP_TLS_VERIFY",   value: "true" },
      { key: "OPENAI_API_KEY",        value: "{{openai_api_key}}" },
      { key: "MCP_SEI_AGENT_URL",     value: "http://mcp-server-sei-agent.mcp-server-sei-agent.svc.cluster.local:3000/mcp" },
    ],
    subSteps: [
      { id: "redis", name: "Redis", playbook: "deploy-redis.yml" },
      { id: "rbac", name: "RBAC / ServiceAccount", playbook: "setup-rbac.yml", extraVars: { sa_name: "mcp-sa" } },
      { id: "agent-ai-app", name: "Agent AI App", playbook: "deploy-component.yml", contextDir: "agent-ai" },
    ],
  },
  {
    id: "mcp-inspector",
    name: "MCP Inspector",
    description: "Interface gráfica para testar e depurar servidores MCP",
    icon: "🔍",
    category: "infra",
    order: 8,
    namespace: "mcp-inspector",
    playbook: "deploy-component.yml",
    contextDir: "mcp-inspector",
    port: 6274,
  },
  {
    id: "sei-installer",
    name: "SEI",
    description: "Sistema Eletrônico de Informações - gestão de processos e documentos oficiais",
    icon: "https://www.gov.br/pt-br/apps/sei/@@images/imagem/mini",
    category: "gov",
    order: 9,
    namespace: "sei-installer",
    playbook: "deploy-component.yml",
    port: 80,
    subSteps: [
      {
        id: "sei-app",
        name: "Deploy SEI (imagem)",
        playbook: "deploy-component.yml",
        critical: true,
        extraVars: {
          app_name: "sei-installer",
          app_image: "quay.io/ricardi/sei-installer",
        },
      },
      {
        id: "sei-pvc",
        name: "PVC /app/config (2Gi)",
        playbook: "attach-pvc.yml",
        extraVars: {
          app_name: "sei-installer",
          pvc_name: "sei-config",
          pvc_size: "2Gi",
          pvc_mount_path: "/app/config",
        },
      },
    ],
  },
];

export const CATEGORIES = {
  infra: { label: "Infraestrutura", color: "#2196F3" },
  mcp: { label: "MCP Servers", color: "#9C27B0" },
  demo: { label: "Demo", color: "#FF9800" },
  core: { label: "Core", color: "#4CAF50" },
  gov: { label: "Governo", color: "#1976D2" },
};

// ============================================================
// Ofertas — pacotes pré-definidos de componentes para demos
// ============================================================

export const OFERTAS = [
  {
    id: "demo-governo",
    name: "Demo para Governo",
    description: "Demonstração completa para o setor público: agente de IA com acesso a dados de saúde e matrículas escolares.",
    icon: "🏛️",
    color: "#1976D2",    // System prompt que será aplicado automaticamente no agent-ai ao abrir esta oferta
    systemPrompt: "Você é um agente de governo que faz algumas ações, algumas informando e outras agindo, como o caso de matrículas e dados de saúde quando está conectado com MCP server. Você também tem acesso ao SEI (Sistema Eletrônico de Informações) para consultar e criar processos e documentos oficiais. Você deve evitar, respeitosamente, que responda coisas não relacionadas ao governo. Coisas básicas como horário e coisas que estão no RAG, você pode responder.",    // Componentes que fazem parte desta oferta (devem existir em COMPONENTS)
    componentIds: ["agent-ai", "mcp-inspector", "mcp-server-matriculas", "mcp-server-saude", "mcp-server-sei", "mcp-server-sei-agent", "sei-installer"],
    // Nodos na topologia (centro + satélites)
    topology: {
      center: { label: "Governo", icon: "🏛️", color: "#1976D2" },
      nodes: [
        { componentId: "agent-ai",              label: "Agent AI",       icon: "🤖", color: "#4CAF50" },
        { componentId: "mcp-inspector",         label: "MCP Inspector",  icon: "🔍", color: "#FF9800" },
        { componentId: "mcp-server-matriculas", label: "Matrículas",     icon: "🎓", color: "#9C27B0" },
        { componentId: "mcp-server-saude",      label: "Saúde",          icon: "🏥", color: "#E91E63" },
        { componentId: "mcp-server-sei",        label: "MCP SEI",        icon: "📄", color: "#0D47A1" },
        { componentId: "mcp-server-sei-agent",  label: "SEI Agent",      icon: "🏛️", color: "#1565C0" },
        { componentId: "sei-installer",         label: "SEI",            icon: "https://www.gov.br/pt-br/apps/sei/@@images/imagem/mini", color: "#1976D2" },
      ],
    },
  },
  {
    id: "demo-aiops",
    name: "Demo para AIOps",
    description: "Demonstração de AIOps: agente de IA com visibilidade completa do cluster Kubernetes — métricas, segurança e troubleshooting inteligente.",
    icon: "🧠",
    color: "#00897B",
    // System prompt null = remove qualquer prompt customizado, usa o padrão do agente (K8s/OpenShift)
    systemPrompt: null,
    componentIds: ["agent-ai", "mcp-inspector", "mcp-server-k8s-live", "mcp-server-k8s-security"],
    topology: {
      center: { label: "AIOps", icon: "🧠", color: "#00897B" },
      nodes: [
        { componentId: "agent-ai",                label: "Agent AI",      icon: "🤖", color: "#4CAF50" },
        { componentId: "mcp-inspector",           label: "MCP Inspector", icon: "🔍", color: "#FF9800" },
        { componentId: "mcp-server-k8s-live",     label: "K8s Live",      icon: "📊", color: "#2196F3" },
        { componentId: "mcp-server-k8s-security", label: "K8s Security",  icon: "🛡️", color: "#E91E63" },
      ],
    },
  },
];
