// ============================================================
// demo-deployer/src/config.js — Configuração dos componentes
// ============================================================

export const COMPONENTS = [
  {
    id: "namespace",
    name: "Namespace",
    description: "Criar namespace/projeto no OpenShift",
    icon: "📁",
    category: "infra",
    order: 0,
    playbook: "deploy-component.yml",
    playbookAction: "common-only",
    required: true,
  },
  {
    id: "redis",
    name: "Redis",
    description: "Cache e vector store para RAG / memória de chat",
    icon: "🗄️",
    category: "infra",
    order: 1,
    playbook: "deploy-redis.yml",
    contextDir: null,
    required: true,
  },
  {
    id: "rbac",
    name: "RBAC / ServiceAccount",
    description: "ServiceAccount + permissões para MCP servers de Kubernetes",
    icon: "🔐",
    category: "infra",
    order: 2,
    playbook: "setup-rbac.yml",
    required: true,
  },
  {
    id: "mcp-server-k8s-live",
    name: "MCP Server K8s Live",
    description: "Métricas, pods, deployments, eventos, VPA, bin packing do cluster",
    icon: "📊",
    category: "mcp",
    order: 3,
    playbook: "deploy-component.yml",
    contextDir: "mcp-server-k8s-live",
    port: 3000,
    envVars: [
      { key: "K8S_API_URL", value: "{{ocp_api_url}}" },
      { key: "K8S_BEARER_TOKEN", value: "{{sa_token}}" },
      { key: "K8S_SKIP_TLS_VERIFY", value: "true" },
    ],
  },
  {
    id: "mcp-server-k8s-security",
    name: "MCP Server K8s Security",
    description: "NetworkPolicies, logs de segurança, namespaces",
    icon: "🛡️",
    category: "mcp",
    order: 4,
    playbook: "deploy-component.yml",
    contextDir: "mcp-server-k8s-security",
    port: 3000,
    envVars: [
      { key: "K8S_API_URL", value: "{{ocp_api_url}}" },
      { key: "K8S_BEARER_TOKEN", value: "{{sa_token}}" },
      { key: "K8S_SKIP_TLS_VERIFY", value: "true" },
    ],
  },
  {
    id: "mcp-server-downdetector",
    name: "MCP Server Downdetector",
    description: "Verificação de status de websites (uptime/downtime)",
    icon: "🌐",
    category: "mcp",
    order: 5,
    playbook: "deploy-component.yml",
    contextDir: "mcp-server-downdetector",
    port: 3000,
  },
  {
    id: "mcp-server-saude",
    name: "MCP Server Saúde",
    description: "Dados de saúde escolar dos alunos",
    icon: "🏥",
    category: "mcp",
    order: 6,
    playbook: "deploy-component.yml",
    contextDir: "mcp-server-saude",
    port: 3001,
  },
  {
    id: "mcp-server-matriculas",
    name: "MCP Server Matrículas",
    description: "Dados de matrículas de alunos",
    icon: "🎓",
    category: "mcp",
    order: 7,
    playbook: "deploy-component.yml",
    contextDir: "mcp-server-matriculas",
    port: 3000,
  },
  {
    id: "imagem-crash",
    name: "Imagem Crash (Demo)",
    description: "Container que entra em CrashLoopBackOff para demonstração",
    icon: "💥",
    category: "demo",
    order: 8,
    playbook: "deploy-component.yml",
    contextDir: "imagem-crash",
    port: 8080,
  },
  {
    id: "agent-ai",
    name: "Agent AI (Chatbot)",
    description: "Chatbot com Quarkus + LangChain4j — orquestrador principal",
    icon: "🤖",
    category: "core",
    order: 9,
    playbook: "deploy-component.yml",
    contextDir: "agent-ai",
    port: 8080,
    envVars: [
      { key: "REDIS_URL", value: "redis://redis:6379" },
    ],
  },
];

export const CATEGORIES = {
  infra: { label: "Infraestrutura", color: "#2196F3" },
  mcp: { label: "MCP Servers", color: "#9C27B0" },
  demo: { label: "Demo", color: "#FF9800" },
  core: { label: "Core", color: "#4CAF50" },
};
